version: '3'
services:
  prometheus:
    image: bitnami/prometheus:2.41.0
    restart: always
    container_name: prometheus
    privileged: true
    environment:
      TZ: Asia/Shanghai
    ports:
      - 9090:9090
    depends_on:
      - alertmanager
      - pushgateway
      - blackbox_exporter
    volumes:  
      - ./prometheus/conf/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
      - ./prometheus/data:/opt/bitnami/prometheus/data
      - ./prometheus/rules:/opt/bitnami/prometheus/rules
      - ./prometheus/blackbox:/opt/bitnami/prometheus/blackbox
    command: 
      - '--config.file=/opt/bitnami/prometheus/conf/prometheus.yml'
      - '--storage.tsdb.path=/opt/bitnami/prometheus/data'
      - '--web.listen-address=:9090'
      - '--web.max-connections=1024'
      - '--query.max-concurrency=1024'
      - '--storage.tsdb.retention=30d'
      - '--storage.tsdb.retention.size=2TB'
      - '--web.enable-lifecycle'
      - '--storage.tsdb.no-lockfile'
    networks:
      - net-prometheus

  grafana:
    image: grafana/grafana:9.3.6
    restart: always
    container_name: grafana
    privileged: true
    ports:
      - "3000:3000"
    volumes:
      #- ./conf/grafana:/etc/grafana
      - ./grafana/data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - net-prometheus

  alertmanager:
    image: bitnami/alertmanager:0.27.0
    restart: always
    container_name: alertmanager
    privileged: true
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager/data:/var/lib/alertmanager
    networks:
      - net-prometheus

  pushgateway:
    image: bitnami/pushgateway:1.9.0
    restart: always
    container_name: pushgateway
    privileged: true
    ports:
      - "9091:9091"
    volumes:
      - ./pushgateway/data:/var/lib/pushgateway
    networks:
      - net-prometheus

  blackbox_exporter:
    image: bitnami/blackbox-exporter:0.25.0
    restart: always
    container_name: blackbox_exporter
    ports:
      - "9115:9115"
    volumes:
      - ./blackbox_exporter/conf/blackbox.yml:/opt/bitnami/blackbox-exporter/blackbox.yml
    networks:
      - net-prometheus

networks:
  net-prometheus:
    driver: bridge
